-- 1. Перемикаємося на плаговану базу даних образу Oracle Free
ALTER SESSION SET CONTAINER = FREEPDB1;

-- 2. Створюємо ізольованого користувача для додатку
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER AI_MENTOR IDENTIFIED BY "@8ffzPFnUbfM"';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE VIEW, UNLIMITED TABLESPACE TO AI_MENTOR';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN RAISE; END IF; -- Пропускаємо помилку, якщо користувач вже існує
END;
/

-- 3. Перемикаємо схему: всі таблиці нижче створяться всередині AI_MENTOR
ALTER SESSION SET CURRENT_SCHEMA = AI_MENTOR;

-- =========================================================================
-- CLEANUP EXISTING OBJECTS
-- =========================================================================
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN 
        ('LLMSESSIONS', 'CERTIFICATES', 'TASKACCESSRULES', 'SUBSCRIPTIONS', 
         'SUBSCRIPTIONPLANS', 'PROGRESS', 'TASKPROMPTS', 'TASKS', 
         'COURSES', 'PROFILETECHNOLOGIES', 'TECHNOLOGIES', 'PROFILES', 'USERS'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- =========================================================================
-- SECURE SYSTEM ACCOUNTS
-- =========================================================================
CREATE TABLE Users (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email VARCHAR2(150) NOT NULL,
    PasswordHash VARCHAR2(255) NOT NULL,
    Role VARCHAR2(30) DEFAULT 'student' NOT NULL,
    IsActive NUMBER(1) DEFAULT 1 NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (Email),
    CONSTRAINT chk_users_role CHECK (Role IN ('student', 'admin', 'instructor', 'moderator')),
    CONSTRAINT chk_users_active CHECK (IsActive IN (0,1))
);

-- =========================================================================
-- AI CONFIGURATION PROFILES
-- =========================================================================
CREATE TABLE Profiles (
    ProfileID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProfileName VARCHAR2(100) NOT NULL,
    Description VARCHAR2(1000),
    PreferredDifficulty VARCHAR2(20) DEFAULT 'easy',
    AIThinkingMode VARCHAR2(50),
    IsDefault NUMBER(1) DEFAULT 0 NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_profile_difficulty CHECK (PreferredDifficulty IN ('easy', 'medium', 'hard')),
    CONSTRAINT chk_profile_default CHECK (IsDefault IN (0,1))
);

-- =========================================================================
-- KNOWLEDGE DOMAINS
-- =========================================================================
CREATE TABLE Technologies (
    TechnologyID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Category VARCHAR2(100),
    Description VARCHAR2(2000),
    CONSTRAINT uq_technology_name UNIQUE (Name)
);

-- =========================================================================
-- INTERSECTION PROFILE TECHNOLOGIES
-- =========================================================================
CREATE TABLE ProfileTechnologies (
    ProfileTechnologyID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProfileID NUMBER NOT NULL,
    TechnologyID NUMBER NOT NULL,
    PriorityLevel NUMBER DEFAULT 1,
    CONSTRAINT fk_profiletech_profile FOREIGN KEY (ProfileID) REFERENCES Profiles(ProfileID) ON DELETE CASCADE,
    CONSTRAINT fk_profiletech_technology FOREIGN KEY (TechnologyID) REFERENCES Technologies(TechnologyID) ON DELETE CASCADE,
    CONSTRAINT uq_profile_technology UNIQUE (ProfileID, TechnologyID)
);

-- =========================================================================
-- COURSES MATRIX
-- =========================================================================
CREATE TABLE Courses (
    CourseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TechnologyID NUMBER NOT NULL,
    Title VARCHAR2(150) NOT NULL,
    Description CLOB,
    LevelType VARCHAR2(20) DEFAULT 'beginner',
    IsPublished NUMBER(1) DEFAULT 1 NOT NULL,
    CreatedBy NUMBER,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_courses_technology FOREIGN KEY (TechnologyID) REFERENCES Technologies(TechnologyID) ON DELETE CASCADE,
    CONSTRAINT fk_courses_creator FOREIGN KEY (CreatedBy) REFERENCES Users(UserID) ON DELETE SET NULL,
    CONSTRAINT chk_course_level CHECK (LevelType IN ('beginner', 'intermediate', 'advanced', 'expert')),
    CONSTRAINT chk_course_published CHECK (IsPublished IN (0,1))
);

-- =========================================================================
-- CODING TASKS ENGINE
-- =========================================================================
CREATE TABLE Tasks (
    TaskID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CourseID NUMBER NOT NULL,
    Title VARCHAR2(200) NOT NULL,
    TaskDescription CLOB NOT NULL,
    Difficulty VARCHAR2(20) NOT NULL,
    EstimatedMinutes NUMBER,
    IsFree NUMBER(1) DEFAULT 0 NOT NULL,
    IsPublished NUMBER(1) DEFAULT 1 NOT NULL,
    SortOrder NUMBER DEFAULT 1,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tasks_course FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE,
    CONSTRAINT chk_task_difficulty CHECK (Difficulty IN ('easy', 'medium', 'hard')),
    CONSTRAINT chk_task_free CHECK (IsFree IN (0,1)),
    CONSTRAINT chk_task_published CHECK (IsPublished IN (0,1))
);

-- =========================================================================
-- SYSTEM TASK PROMPTS
-- =========================================================================
CREATE TABLE TaskPrompts (
    PromptID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TaskID NUMBER NOT NULL,
    PromptType VARCHAR2(50) NOT NULL,
    PromptContent CLOB NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prompts_task FOREIGN KEY (TaskID) REFERENCES Tasks(TaskID) ON DELETE CASCADE
);

-- =========================================================================
-- PROGRESS RECORDING MATRIX
-- =========================================================================
CREATE TABLE Progress (
    ProgressID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER NOT NULL,
    TaskID NUMBER NOT NULL,
    Status VARCHAR2(30) DEFAULT 'pending' NOT NULL,
    Score NUMBER DEFAULT 0,
    Attempts NUMBER DEFAULT 0,
    LastLLMFeedback CLOB,
    StartedAt TIMESTAMP,
    CompletedAt TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_progress_user FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_progress_task FOREIGN KEY (TaskID) REFERENCES Tasks(TaskID) ON DELETE CASCADE,
    CONSTRAINT uq_user_task UNIQUE (UserID, TaskID),
    CONSTRAINT chk_progress_status CHECK (Status IN ('pending', 'in_progress', 'completed', 'failed', 'locked')),
    CONSTRAINT chk_progress_score CHECK (Score BETWEEN 0 AND 100)
);

-- =========================================================================
-- SUBSCRIPTION PLANS TIER
-- =========================================================================
CREATE TABLE SubscriptionPlans (
    PlanID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(50) NOT NULL,
    Description VARCHAR2(1000),
    MonthlyPrice NUMBER(10,2) DEFAULT 0,
    HasFullAccess NUMBER(1) DEFAULT 0,
    HasPartialAccess NUMBER(1) DEFAULT 0,
    DailyLLMLimit NUMBER DEFAULT 10,
    CONSTRAINT uq_plan_name UNIQUE (Name),
    CONSTRAINT chk_plan_full CHECK (HasFullAccess IN (0,1)),
    CONSTRAINT chk_plan_partial CHECK (HasPartialAccess IN (0,1))
);

-- =========================================================================
-- SUBSCRIPTIONS RECORDS
-- =========================================================================
CREATE TABLE Subscriptions (
    SubscriptionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER NOT NULL,
    PlanID NUMBER NOT NULL,
    StartDate DATE DEFAULT CURRENT_DATE NOT NULL,
    ExpiryDate DATE NOT NULL,
    Status VARCHAR2(20) DEFAULT 'active' NOT NULL,
    AutoRenew NUMBER(1) DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscription_user FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_plan FOREIGN KEY (PlanID) REFERENCES SubscriptionPlans(PlanID),
    CONSTRAINT chk_subscription_status CHECK (Status IN ('active', 'expired', 'cancelled', 'pending')),
    CONSTRAINT chk_subscription_renew CHECK (AutoRenew IN (0,1))
);

-- =========================================================================
-- TASK ACCESS GATE RULES
-- =========================================================================
CREATE TABLE TaskAccessRules (
    AccessRuleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TaskID NUMBER NOT NULL,
    PlanID NUMBER NOT NULL,
    IsAccessible NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_access_task FOREIGN KEY (TaskID) REFERENCES Tasks(TaskID) ON DELETE CASCADE,
    CONSTRAINT fk_access_plan FOREIGN KEY (PlanID) REFERENCES SubscriptionPlans(PlanID) ON DELETE CASCADE,
    CONSTRAINT uq_task_plan_access UNIQUE (TaskID, PlanID),
    CONSTRAINT chk_accessible CHECK (IsAccessible IN (0,1))
);

-- =========================================================================
-- CERTIFICATES GENERATION LOGIC
-- =========================================================================
CREATE TABLE Certificates (
    CertificateID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER NOT NULL,
    CourseID NUMBER NOT NULL,
    CertificateCode VARCHAR2(100) NOT NULL,
    IssuedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FinalScore NUMBER,
    CONSTRAINT fk_cert_user FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_cert_course FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE,
    CONSTRAINT uq_user_course_cert UNIQUE (UserID, CourseID),
    CONSTRAINT uq_certificate_code UNIQUE (CertificateCode)
);

-- =========================================================================
-- LLM INTERACTION METRICS
-- =========================================================================
CREATE TABLE LLMSessions (
    SessionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER NOT NULL,
    ProfileID NUMBER,
    TaskID NUMBER,
    PromptTokens NUMBER DEFAULT 0,
    ResponseTokens NUMBER DEFAULT 0,
    ModelName VARCHAR2(100),
    StartedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FinishedAt TIMESTAMP,
    Status VARCHAR2(20) DEFAULT 'active',
    CONSTRAINT fk_llm_user FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_llm_profile FOREIGN KEY (ProfileID) REFERENCES Profiles(ProfileID) ON DELETE SET NULL,
    CONSTRAINT fk_llm_task FOREIGN KEY (TaskID) REFERENCES Tasks(TaskID) ON DELETE SET NULL,
    CONSTRAINT chk_llm_status CHECK (Status IN ('active', 'completed', 'failed'))
);

-- =========================================================================
-- INITIAL WORKSPACE core SEED DATA
-- =========================================================================
INSERT INTO SubscriptionPlans (Name, Description, MonthlyPrice, HasFullAccess, HasPartialAccess, DailyLLMLimit) VALUES ('FREE', 'Limited access to free tasks', 0, 0, 0, 10);
INSERT INTO SubscriptionPlans (Name, Description, MonthlyPrice, HasFullAccess, HasPartialAccess, DailyLLMLimit) VALUES ('PRO', 'Partial access to premium tasks', 19.99, 0, 1, 500);
INSERT INTO SubscriptionPlans (Name, Description, MonthlyPrice, HasFullAccess, HasPartialAccess, DailyLLMLimit) VALUES ('ENTERPRISE', 'Full access to all tasks and advanced AI', 49.99, 1, 1, 5000);

COMMIT;
/