worker_processes auto;

events {
    worker_connections 8192;
    multi_accept on;
}

http {
    # Балансування бекенду (Round Robin за замовчуванням)
    upstream api_backend {
        server backend:5000;
    }

    # Балансування фронтенду
    upstream ui_frontend {
        server frontend:3000;
    }

    server {
        listen 80;

        # Маршрутизація API запитів на Backend
        location /api/ {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Усі інші запити йдуть на Frontend
        location / {
            proxy_pass http://ui_frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}